import type { SpecialistDoctor } from '../types/api.js';

export const specialists: SpecialistDoctor[] = [
  { id: 'doc-1', name: 'Dr. Vivek Raghavan', specialty: 'Senior Consultant Cardiologist', degree: 'MD, DM (Cardiology), FACC', hospital: 'Manipal Hospital, Old Airport Road', distanceKm: 2.8, rating: 4.9, experienceYears: 19, consultationFee: '₹1,000', address: '98 HAL Airport Rd, Kodihalli, Bengaluru', matchingOrgans: ['heart'], teleconsultAvailable: true, nextSlot: 'Tomorrow at 10:30 AM' },
  { id: 'doc-2', name: 'Dr. Ananya Sengupta', specialty: 'Consultant Orthopedic & Spine Surgeon', degree: 'MS (Ortho), Fellowship in Spine Surgery (UK)', hospital: 'Apollo Spectra Hospitals, Koramangala', distanceKm: 4.2, rating: 4.8, experienceYears: 15, consultationFee: '₹900', address: '143 5th Block, Koramangala, Bengaluru', matchingOrgans: ['spine', 'knees'], teleconsultAvailable: true, nextSlot: 'Thursday at 04:00 PM' },
  { id: 'doc-3', name: 'Dr. Ramesh Sundaram', specialty: 'Endocrinologist & Diabetes Specialist', degree: 'MD (Med), DM (Endocrinology)', hospital: 'Fortis Hospital, Cunningham Road', distanceKm: 6.5, rating: 4.9, experienceYears: 22, consultationFee: '₹1,200', address: '14 Cunningham Rd, Vasanth Nagar, Bengaluru', matchingOrgans: ['liver', 'stomach'], teleconsultAvailable: true, nextSlot: 'Friday at 11:15 AM' },
  { id: 'doc-4', name: 'Dr. Meera Nambiar', specialty: 'Consultant Pulmonologist & Sleep Medicine', degree: 'DNB (Respiratory Diseases), FCCP', hospital: 'Aster CMI Hospital, Hebbal', distanceKm: 8.9, rating: 4.7, experienceYears: 13, consultationFee: '₹850', address: 'No. 43/2 New Airport Rd, Sahakar Nagar, Bengaluru', matchingOrgans: ['lungs'], teleconsultAvailable: true, nextSlot: 'Tomorrow at 02:30 PM' },
  { id: 'doc-5', name: 'Dr. Arvind Kulkarni', specialty: 'Consultant Neurologist', degree: 'MD, DM (Neurology), NIMHANS', hospital: 'Narayana Multispeciality Hospital, HSR', distanceKm: 5.1, rating: 4.9, experienceYears: 18, consultationFee: '₹1,100', address: 'Sector 3, HSR Layout, Bengaluru', matchingOrgans: ['brain', 'spine'], teleconsultAvailable: false, nextSlot: 'Wednesday at 05:00 PM' },
];
